mysql_host: 172.21.203.3
spring:
  data:
    redis:
      host: 172.21.203.3
      port: 6379
      database: 1
      password: xxxx
  datasource:
    druid:
      password: xxxx

  mail:
    username: 1041765757@qq.com
    password: xxx
customizer:
  infra:
    s3:
      enable: true
      endpoint: http://172.21.203.3:9000
      access-key: xxx
      secret-key: xxx
      bucket-name: group-purchase
      region: cn-bj1
      secure: false
      path-style-access: true
