mysql_host: 10.88.1.23
spring:
  data:
    redis:
      host: 10.88.1.23
      port: 6379
      database: 1
      password: ItIsSnowball
  datasource:
    druid:
      password: ItIsSnowball

  mail:
    username: 1041765757@qq.com
    password: xxx
customizer:
  infra:
    s3:
      enable: true
      endpoint: http://10.88.1.23:9000
      access-key: xxx
      secret-key: xxx
      bucket-name: group-purchase
      region: cn-bj1
      secure: false
      path-style-access: true
